miniquizapp/miniquizapp/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),

    path('quizzes/', include('quizzes.urls')),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

miniquizapp/quizzes/urls.py
from django.urls import path
from . import views

app_name = 'quizzes'
urlpatterns = [
    path('category/<slug:slug>', views.QuizCategoryDetailView.as_view(), name="quiz_category_detail_view"),
    path('categories/', views.QuizCategoryListView.as_view(), name="quiz_category_list_view"),
]

miniquizapp/home/models.py
from django.db import models

from wagtail.core.models import Page


class HomePage(Page):
    pass

miniquizapp/quizzes/models.py
from django import forms
from django.db import models

from wagtail.core.models import Page, Orderable
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel
from modelcluster.fields import ParentalKey, ParentalManyToManyField

# Create your models here.
class QuizCategory(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        null=False, 
        unique=True
    )
    slug = models.SlugField(
        max_length=255, 
        unique=True, 
        help_text='This will be how the category appears in urls eg. sitename/category/slug'
    )

    panels = [
        FieldPanel('name'),
        FieldPanel('slug')
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'quiz categories'

class QuizIndexPage(Page):
    intro = RichTextField(blank=False, null=False, help_text='Enter a short introduction to the index page which lists all quizzes.')

    def get_context(self, request):
        context = super().get_context(request)
        quiz_pages = self.get_children().live().order_by('title')
        context['quiz_pages'] = quiz_pages
        return context

    content_panels = Page.content_panels + [
        FieldPanel('intro')
    ]

class QuizPage(Page):
    intro = models.TextField(
        blank=False,
        null=False,
        help_text='Give a very brief introduction to this quiz.'
    )
    date = models.DateField("Quiz Creation Date")
    categories = ParentalManyToManyField('quizzes.QuizCategory', blank=True)

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('intro'),
        ], heading='General'),
        FieldPanel('categories', widget=forms.CheckboxSelectMultiple),
        InlinePanel('quiz_questions', label='Quiz Questions')
    ]

    def get_context(self, request):
        context = super().get_context(request)
        session = request.session
        request.session['most_recent_quiz_title'] = self.title
        request.session['most_recent_quiz_url'] = self.url
        return context


class QuizQuestion(Orderable):
    page = ParentalKey(QuizPage, on_delete=models.CASCADE, related_name='quiz_questions')
    question = models.CharField(
        max_length=255,
        unique=False,
        blank=False,
        null=False,
        help_text='Enter a question.'
    )
    answer = models.CharField(
        max_length=400,
        unique=False,
        blank=False,
        null=False,
        help_text='Enter the answer.'
    )

    panels = [
        FieldPanel('question'),
        FieldPanel('answer')
    ]

miniquizapp/quizzes/views.py
from django.shortcuts import render
from django.views import generic
from .models import QuizCategory

# Create your views here.
class QuizCategoryDetailView(generic.DetailView):
    model = QuizCategory
    template_name = 'quizzes/quiz_category_detail_view.html'

    def get_queryset(self):
        return QuizCategory.objects.all()

class QuizCategoryListView(generic.ListView):
    model = QuizCategory
    template_name = 'quizzes/quiz_category_list_view.html'

    def get_queryset(self):
        return QuizCategory.objects.all()

miniquizapp/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

miniquizapp/home/templates/home/home_page.html
{% extends "base.html" %}

{% load static %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}

<!-- Loads template tags in 'quizzes/templatetags/quiz_categories.py' --->
{% load quiz_categories %}


{% block content %}

<!-- Displays 'tags/get_latest_quizzes.html' -->
<div class="homepage-container-fluid container-fluid">
    {% get_latest_quizzes %}
</div>

<!-- Call to action to visit Quiz Index Page -->
<div class="container-fluid bg-primary">
	<div class="section container">
        <div class="text-center text-white">
            <span class="h2 text-white pr-4">
                <strong>Browse all quizzes on our Quiz Index Page</strong>
            </span>
            <a href="{% slugurl 'quiz-index-page' %}">
                <button class="btn btn-light">Browse all quizzes!</button>
            </a>
        </div>
    </div>
</div>

<!-- Display 'tags/get_all_categories.html' -->
<div class="homepage-section">
    {% get_all_categories %}
</div>

{% endblock content %}

miniquizapp/miniquizapp/templates/base.html
{% load static wagtailuserbar %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}
 
<!-- From the package 'django_compressor' -->
{% load compress %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/miniquizapp.css' %}">

        <!-- 'theme.scss' file inherits and overrides bootstrap scss files -->
        <!-- Check 'settings/base.py' to see how django-libsass and django_compressor are setup -->
        {% compress css %}
        <link type="text/x-scss" href="{% static 'theme.scss' %}" rel="stylesheet" media="screen">
        {% endcompress %}

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

        <!-- From 'main_menu.html'-->
        {% include 'main_menu.html' %}

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/miniquizapp.js' %}"></script>

        {# Bootstrap javascript #}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

miniquizapp/miniquizapp/templates/main_menu.html
{% load wagtailcore_tags %}

<div class="container-fluid bg-white shadow-sm">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    	
	    <a class="navbar-brand text-primary" href="{% slugurl 'home' %}">
	      Mini Quiz App
	    </a>  
 
	    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>

	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	        <ul class="navbar-nav ml-auto">
	            <li class="nav-item mr-3 active">
	                <a class="nav-link text-primary" href="{% slugurl 'home' %}">Home <span class="sr-only">(current)</span></a>
	            </li>
	            <li class="nav-item mr-3">
	                <a class="nav-link text-primary" href="{% url 'quizzes:quiz_category_list_view' %}">Quiz Categories</a>
	            </li>
	            <li class="nav-item mr-3">
	                <a class="nav-link text-primary" href="{% slugurl 'quiz-index-page' %}">Quiz Index</a>
	            </li>
	            <li>
                    <button class="btn btn-outline-success">Contact!</button>
	            </li>
	        </ul>
	    </div>
        </nav>
    </div>
</div>

miniquizapp/quizzes/templates/quizzes/quiz_category_detail_view.html
{% extends "base.html" %}

{% load static %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}

<!-- Loads template tags in 'quizzes/templatetags/quiz_categories.py' --->
{% load quiz_categories %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <div class="col-md-3 bg-primary p-5 text-white">
            <!-- Displays last quiz visited -->
            {% if latest_quiz_visited_info %}
                <h5><strong>Recently visited:</strong></h5>
                <p>
                    <a class="text-white" href="{{ latest_quiz_visited_info.url }}">
                        <small>{{ latest_quiz_visited_info.title }}</small>
                    </a>
                </p>
            {% endif %}
            <!-- Display categories -->
            {% get_categories_sidebar %}
        </div>

        <div class="col-md-9">
            <div class="section container">
        
                <div class="section-title">
                    <h5>QUIZ CATEGORY:</h5>
                    <h2>{{ quizcategory.name }}</h2>
                </div>

                <div class="row">
                    {% for quiz in quizcategory.quizpage_set.all %}
                    <div class="col-md-6 col-lg-4 mb-3">
                        <div class="question-box text-center">
                            <h5>
                                <a href="{% pageurl quiz %}">{{ quiz.title }}</a>
                            </h5>
                            <p><small>{{ quiz.specific.intro }}</small></p>
                        </div>
                    </div>
                    {% endfor %}
                </div><!-- End row-->

            </div><!-- End section container-->

        </div>
    </div><!-- End row -->
</div><!-- End container-fluid-->


{% endblock %}

miniquizapp/quizzes/templates/quizzes/quiz_category_list_view.html
{% extends "base.html" %}

{% load static %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}

<!-- Loads template tags in 'quizzes/templatetags/quiz_categories.py' --->
{% load quiz_categories %}

{% block content %}

<div class="container-fluid">
    <div class="row">

    	<!-- Sidebar -->
    	<div class="col-md-3 bg-primary p-5 text-white">
    		<!-- Displays last quiz visited -->
    		{% if latest_quiz_visited_info %}
				<h5><strong>Recently visited:</strong></h5>
				<p>
					<a class="text-white" href="{{ latest_quiz_visited_info.url }}">
					    <small>{{ latest_quiz_visited_info.title }}</small>
					</a>
				</p>
			{% endif %}
			<!-- Displays all quizzes -->
            {% get_quizzes_sidebar %}
        </div>

        <div class="col-md-9">
            {% get_all_categories %}
        </div>

    </div><!-- End row -->
</div><!-- End container-fluid-->



{% endblock %}

miniquizapp/quizzes/templates/quizzes/quiz_index_page.html
{% extends 'base.html' %}

{% load static %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}

<!-- Loads template tags in 'quizzes/templatetags/quiz_categories.py' --->
{% load quiz_categories %}

{% block content %}

<div class="container-fluid">
    <div class="row">

    	<div class="col-md-3 bg-primary p-5 text-white">
    		<!-- Displays last quiz visited -->
            {% if latest_quiz_visited_info %}
                <h5><strong>Recently visited:</strong></h5>
                <p>
                    <a class="text-white" href="{{ latest_quiz_visited_info.url }}">
                        <small>{{ latest_quiz_visited_info.title }}</small>
                    </a>
                </p>
            {% endif %}
            <!-- Displays categories in sidebar--->
            {% get_categories_sidebar %}
        </div>

        <div class="col-md-9 px-4">
        	<div class="section container">
                <div class="section-title">
				    <h2>Quiz Index</h2>
				    {{ page.intro|richtext }}
			    </div>
			    {% for quiz in quiz_pages %}
			    <div class="row question-box text-center mb-4">
		            <div class="col-md-4">
			            <h5>
				            <a href="{% pageurl quiz %}">{{ quiz.title }}</a>
				        </h5>
			        </div>
			        <div class="col-md-8">
                        <p><small>{{ quiz.specific.intro }}</small></p>
			        </div>
	            </div><!-- End row-->
	            {% endfor %}
        	</div><!-- End section container -->
        </div><!-- End col-md-9 -->

    </div><!-- End row -->
</div><!-- End container fluid-->

{% endblock %}

miniquizapp/quizzes/templates/quizzes/quiz_page.html
{% extends "base.html" %}

{% load static %}

<!-- Loads wagtail template tags -->
{% load wagtailcore_tags %}

<!-- Loads template tags in 'quizzes/templatetags/quiz_categories.py' --->
{% load quiz_categories %}

{% block content %}

<div class="container-fluid">
    <div class="row">
    	<div class="col-md-3 bg-primary p-5 text-white">
    		<!-- Displays categories in sidebar -->
            {% get_categories_sidebar %}
        </div>

        <div class="col-md-9">
      
	        <div class="section container">

				<div class="section-title">
					<h2>{{ page.title }}</h2>
					{{ page.intro|richtext }}
					<p class="py-3"><small>Categories:</small>
		            {% for category in page.categories.all %}
		                <button class="btn btn-primary btn-sm">
	                    <a class="text-white" href="{% url 'quizzes:quiz_category_detail_view' category.slug %}">
	                    {{ category.name }}
	                    </a>
		                </button>
		            {% endfor %}
		            </p>
				</div>

	            <div class="px-2">
				    <h2>Questions</h2>
					<ol>
					{% for question in page.quiz_questions.all %}
					    <li class="questions">{{ question.question }}</li>
					{% endfor %}
				    </ol>
	            </div>

	            <div class="py-4 text-center">
				    <button class="text-center btn btn-success" id="reveal-answers-button">REVEAL ANSWERS!</button>
	            </div>

	      	    <div class="px-2" id="quiz-answers">
					<h2>Answers</h2>
					<ol>
					{% for question in page.quiz_questions.all %}
					    <li><small>{{ question.question }}</small></li>
					    <p style="font-weight: bold; color:green;">
					    {{ question.answer }}
					    </p>
					{% endfor %}
				    </ol>
			    </div>

		    </div><!-- End section container-->

        </div>
    </div>
</div><!-- End container-fluid-->


{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'quizzes/js/quizzes.js' %}"></script>
{% endblock %}

miniquizapp/quizzes/templates/tags/get_all_categories.html
<div class="section container">
    <div class="section-title">
	    <h2>Browse categories</h2>
	    <p>All categories</p>
    </div>
  
    <div class="row">
  	    {% for category in all_categories %}
        <div class="col-md-4 col-lg-3 mb-3">
	  	    <a href="{% url 'quizzes:quiz_category_detail_view' category.slug %}">
		        <div class="category-box card h-100 bg-primary text-center">
		            <h3 class="text-white">
			            {{ category.name }}
			        </h3>
		        </div>
	        </a>
	    </div>
	    {% endfor %}
    </div><!-- End row -->

</div><!-- End section container -->

miniquizapp/quizzes/templates/tags/get_categories_sidebar.html
<h4><strong>Quiz Categories</strong></h4>
{% for category in categories_sidebar %}
<p>
    <a class="text-white" href="{% url 'quizzes:quiz_category_detail_view' category.slug %}">{{ category.name }}</a>
</p>
{% endfor %}

miniquizapp/quizzes/templates/tags/get_latest_quizzes.html
{% load wagtailcore_tags %}

<div class="section container">

    <div class="section-title">
	    <h2>Welcome to the Mini Quiz App</h2>
	    <p>Here are the most recently added quizzes</p>
    </div>
  
    <div class="row">

  	    {% for quiz in latest_quizzes %}
        <div class="col-md-4 col-lg-3 mb-4">
		    <div class="card h-100 question-box">
			    <a href="{% pageurl quiz %}">
		            <h5>{{ quiz.title }}</h5>
		        </a>
                <p><small>{{ quiz.specific.intro }}</small></p>
		    </div>
	    </div>
	    {% endfor %}

    </div><!-- End row -->

</div><!-- End section container -->

miniquizapp/quizzes/templates/tags/get_questions_sidebar.html
{% load wagtailcore_tags %}

<h4><strong>Quizzes</strong></h4>
{% for page in questions_sidebar %}
<p>
    <a class="text-grey" href="{% pageurl page %}">{{ page.title }}</a>
</p>
{% endfor %}

miniquizapp/quizzes/templates/tags/get_quizzes_sidebar.html
{% load wagtailcore_tags %}

<h4><strong>Quizzes</strong></h4>
{% for page in quizzes_sidebar %}
<p>
    <a class="text-white" href="{% pageurl page %}">{{ page.title }}</a>
</p>
{% endfor %}

miniquizapp/search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Search" class="button">
    </form>

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if search_results.has_previous %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
        {% endif %}

        {% if search_results.has_next %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
        {% endif %}
    {% elif search_query %}
        No results found
    {% endif %}
{% endblock %}